-
  version: '1.0.{build}'
  image: Visual Studio 2017
  branches:
    only:
    - production
  init:
    - cmd: git config --global core.autocrlf true
  before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore RPThreadTrackerV3.BackEnd.TumblrClient.sln --verbosity m
  build_script:
    - cmd: dotnet publish RPThreadTrackerV3.BackEnd.TumblrClient.sln -c Release
  test_script:
    - cmd: sh ./coverage.sh
  after_test:
    - cmd: curl -s https://codecov.io/bash | bash -s -- -f coverage.xml
  artifacts:
    - path: '\RPThreadTrackerV3.BackEnd.TumblrClient\bin\Release\netcoreapp2.2\publish'
      name: WebSite
      type: WebDeployPackage
  deploy:
    - provider: Environment
      name: RPThreadTrackerV3-TumblrClient-Prod
  on_success:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/blackjackkent/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 success $env:WEBHOOK_URL
  on_failure:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/blackjackkent/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 failure $env:WEBHOOK_URL
-
  version: '1.0.{build}'
  image: Visual Studio 2017
  branches:
    only:
    - development
  init:
    - cmd: git config --global core.autocrlf true
  before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore RPThreadTrackerV3.BackEnd.TumblrClient.sln --verbosity m
  build_script:
    - cmd: dotnet publish RPThreadTrackerV3.BackEnd.TumblrClient.sln -c Release
  test_script:
    - cmd: sh ./coverage.sh
  after_test:
    - cmd: curl -s https://codecov.io/bash | bash -s -- -f coverage.xml
  artifacts:
    - path: '\RPThreadTrackerV3.BackEnd.TumblrClient\bin\Release\netcoreapp2.2\publish'
      name: WebSite
      type: WebDeployPackage
  deploy:
    - provider: Environment
      name: RPThreadTrackerV3-TumblrClient-Staging
  on_success:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/blackjackkent/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 success $env:WEBHOOK_URL
  on_failure:
    - ps: Invoke-RestMethod https://raw.githubusercontent.com/blackjackkent/appveyor-discord-webhook/master/send.ps1 -o send.ps1
    - ps: ./send.ps1 failure $env:WEBHOOK_URL
