apiRules:
- exclude:
      uidRegex: ^System\.Object
      type: Type
- exclude:
      uidRegex: ^System\.Exception
      type: Type
- exclude:
      uidRegex: ^Microsoft\.AspNetCore
- exclude:
      uidRegex: ^Microsoft\.Azure
- exclude:
      uidRegex: ^Microsoft\.EntityFrameworkCore
