# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: ["production", "development"]
  pull_request:
    branches: ["production", "development"]

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.2.207
      - run: dotnet restore RPThreadTrackerV3.BackEnd.TumblrClient.sln --verbosity m
      - run: dotnet publish RPThreadTrackerV3.BackEnd.TumblrClient/RPThreadTrackerV3.BackEnd.TumblrClient.csproj -c Release
      - run: sh ./coverage.sh
      - run: curl -s https://codecov.io/bash | bash -s -- -f coverage.xml
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - build-and-test
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
