# This workflow will deploy the application to staging when the development branch is updated.

name: Deploy Production

on:
  push:
    branches:
      - production

jobs:
  deploy-package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 2.2.207
      - run: dotnet restore RPThreadTrackerV3.BackEnd.TumblrClient.sln --verbosity m
      - run: dotnet publish RPThreadTrackerV3.BackEnd.TumblrClient/RPThreadTrackerV3.BackEnd.TumblrClient.csproj -c Release
      - uses: azure/webapps-deploy@v2
        with:
          app-name: "RPThreadTrackerV3-TumblrClient"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs: # make sure the notification is sent AFTER the jobs you want included have completed
      - deploy-package
    if: ${{ always() }} # You always want to be notified: success, failure, or cancelled
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
